Main
onedebos/tic-tac-toe-main pull request #2
Opened 2019-08-15 19:39 UTC by onedebos

2019-08-15 20:00 UTC, onedebos commented
Ruby Tic-tac-toe project.completed.

2019-08-15 21:44 UTC, bellom requested changes
Hi Team,
Great work guys, game well played and nice job using `Git Flow` but you didn't go through all the instructions from pathwright.
_Always read the pathwright instructions before starting a project to avoid multiple code review request, according to the pathwright, `main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used._

_Kindly re-submit for review after making all those changes slightly_smiling_face Thumps -up await you._

2019-08-15 21:44 UTC, bellom commented on lib/game.rb
> +    puts "\n"
`main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used.

2019-08-15 21:44 UTC, bellom commented on lib/game.rb
> +    puts 'Legend'
`main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used._

2019-08-15 21:44 UTC, bellom commented on lib/game.rb
> +    input = gets.chomp.to_i
`main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used._

2019-08-15 21:44 UTC, bellom commented on lib/game.rb
> +      puts ' You need to enter a number between 1 and 9.'
`main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used._

2019-08-15 21:44 UTC, bellom commented on lib/game.rb
> +      puts 'This cell is not available.'
`main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used._

2019-08-15 21:44 UTC, bellom commented on lib/game.rb
> +        puts "#{@current_player.name} wins!"
`main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used._

2019-08-15 21:44 UTC, bellom commented on lib/game.rb
> +      puts "It's a draw."
`main.rb` file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used._

2019-08-16 19:36 UTC, AdnanAfsari requested changes
Hello @onedebos @vieiramanda11 ✋ 

Nice work guys but i think you are yet to make some changes the previous reviewer requested to change, those changes are not big i guess.
Please go ahead and make current those changes and submit for anther review 😄 

Happy Coding

2019-08-19 03:35 UTC, mosaaleb commented on lib/game.rb
> +        did_win
Applying SRP here we can refactor this method into smaller method each does only one thing. As you can see this method:
1. checks for winning.
2. checks for draw.
3. print a message.

We can refactor it like this:
```ruby
def end_game?
    player_wins? || game_draw?
end
```
then we need to implement these methods accordingly.

2019-08-19 03:37 UTC, mosaaleb requested changes
### Well done team :clap:

Yet there are some work we need to do before moving on:

- [ ] When a player enters a number not in (1..9) the application throws an error and exit execution, it need to repeat the process without exiting.

- [ ] The project should have descriptive readme file.

- [ ] (`main.rb` file should be responsible for user interaction) doesn't mean that you wrap the puts and gets inside method and still use them in other classes. `Game` class should not do any kind of interactions even if it is wrapped inside another methods. 
The idea behind this comes from single responsibility principle whereas each class and each method should only do one thing. For example `Game` class should decide if we have reached a winning position or not, then the `main.rb` can use this functionality to `put` a relevant message. Now we have separated the functionality of each class. 

What you have done from the previous review is just moving the interaction messages from one class to a module.

A good indication of applying a single responsibility principle (SRP) is to ask yourself what this `Game` class do, if you said the word (and) then it does too much. In our case `Game` class should only decide the workflow of the game and this can be represnted in multiple methods: `winning?` `draw?` `change_turns` and so on. Then for our class in `main.rb` we need to instantiate a `Game` object and always checking for these methods and hence decide what message we should print to the user.

Please handle these requirements and submit a new code review.

#### Happy Coding :computer:

2019-08-19 03:37 UTC, mosaaleb commented on lib/game.rb
> +        did_win
Applying SRP here we can refactor this method into smaller method each does only one thing. As you can see this method:
1. checks for winning.
2. checks for draw.
3. print a message.

We can refactor it like this:
```ruby
def end_game?
    player_wins? || game_draw?
end
```
then we need to implement these methods accordingly.

2019-08-20 17:27 UTC, maelfosso approved these changes
# Good job :+1: 

You can merge with the `development` branch. 
Good luck with the next project.

`*OPTIONAL*` : Please remove the `Game` class from `main.rb` and create a simple class for it such that it doesn't have user interactions which must only be into `main.rb`. Otherwise, you will have some problem when writing test for that class in the next project.

2019-08-20 18:19 UTC, merged